multiplexed: false
sample_name: "SAMPLE_NAME"
barcodes: "BC01 BC02 BC03 BC04 BC05"
basecall: false

flowcell: "FLO-MIN106"
kit: "SQK-LSK108"
threads: 1
tb_reference: "data/reference/NC_000962.3.fa.gz"

containers:
    albacore: "containers/albacore.simg"
    nanoporeqc: "containers/nanoporeqc.simg"
    mykrobe: "containers/mykrobe.simg"
