barcodes:
    "BC01 BC02 BC03 BC04 BC05"
multiplexed:
    false
sample_name:
    "sample"

flowcell:
    "FLO-MIN106"
kit:
    "SQK-LSK108"
threads:
    32
contamination_reference:
    "data/reference/remove_contam_map-ont.mm2"
tb_reference:
    "data/reference/NC_000962.3.fa"
containers:
    albacore: "containers/albacore.simg"
    nanoporeqc: "containers/nanoporeqc.simg"
    mykrobe: "containers/mykrobe.simg"
